language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5.1"
sudo: false
env:
  - NPM_SCRIPT=lint
  - NPM_SCRIPT=nsp
  - NPM_SCRIPT=test
script:
  - "npm run $NPM_SCRIPT"
matrix:
  exclude:
    - node_js: "0.10"
      env: NPM_SCRIPT=lint
    - node_js: "0.12"
      env: NPM_SCRIPT=lint
    - node_js: "4.2"
      env: NPM_SCRIPT=lint
    - node_js: "0.10"
      env: NPM_SCRIPT=nsp
    - node_js: "0.12"
      env: NPM_SCRIPT=nsp
    - node_js: "4.2"
      env: NPM_SCRIPT=nsp
